services:
  - type: web
    name: discord-mod-bot
    env: python
    pythonVersion: "3.11.8"
    buildCommand: |
      python --version
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.8" 